name: Deploy and Restart Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Deploy and Build on Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}

        run: |
          echo "${SSH_PRIVATE_KEY}" > key.pem
          chmod 600 key.pem

          # Создаем временную директорию
          mkdir temp_build_dir

          # Копируем все файлы в эту директорию, исключая .git и .github
          rsync -a --exclude='.git' --exclude='.github' ./ temp_build_dir/

          # Переходим в временную директорию и архивируем проект
          cd temp_build_dir
          tar -czf ../tender.tar.gz .

          # Возвращаемся в исходную директорию и удаляем временную директорию
          cd ..
          rm -rf temp_build_dir

          # Передаем архив на сервер
          scp -i key.pem -P $SERVER_PORT -o StrictHostKeyChecking=no tender.tar.gz $SERVER_USER@$SERVER_HOST:/root/go/src/tender/

          # Распаковываем и собираем проект на сервере
          ssh -i key.pem -p $SERVER_PORT -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
            export PATH=$PATH:/usr/local/go/bin
          
            cd /root/go/src/tender/
            tar -xzf tender.tar.gz
            cd /root/go/src/tender/cmd/tender/
            go build -o tender -buildvcs=false
            sudo systemctl restart tender
          EOF

          # Удаляем ключ и архив
          rm key.pem
          rm tender.tar.gz
