name: Deploy and Restart Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Deploy and Build on Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}

        run: |
          echo "${SSH_PRIVATE_KEY}" > key.pem
          chmod 600 key.pem

          # Архивируем проект перед передачей
          tar -czf tender.tar.gz .

          # Передаем архив на сервер
          scp -i key.pem -P $SERVER_PORT -o StrictHostKeyChecking=no tender.tar.gz $SERVER_USER@$SERVER_HOST:/root/go/src/tender/

          # Распаковываем и собираем проект на сервере
          ssh -i key.pem -p $SERVER_PORT -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
            cd /root/go/src/tender/
            tar -xzf tender.tar.gz
            cd cmd/tender/
            go build -o ./tender .
            sudo systemctl restart tender.service
          EOF

          # Удаляем ключ и архив
          rm /root/go/src/tender/key.pem
          rm /root/go/src/tender/tender.tar.gz
        
