name: Deploy and Restart Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Build Go application
        run: go build -o /root/go/src/tender/cmd/tender/tender

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}

        run: |
          echo "${SSH_PRIVATE_KEY}" > key.pem
          chmod 600 key.pem
          scp -i key.pem -P $SERVER_PORT tender $SERVER_USER@$SERVER_HOST:/usr/local/bin/
          ssh -i key.pem -p $SERVER_PORT $SERVER_USER@$SERVER_HOST "sudo systemctl restart tender.service"
          rm key.pem
